/*
 * This Java source file was generated by the Gradle 'init' task.
 */

import graph2.Graph;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }

    public static void main(String[] args) {
        Graph g1 = new Graph();
        g1.addVertex("1");
        g1.addVertex("2");
        g1.addVertex("3");
        g1.addVertex("4");
//        g1.addVertex("5");

        g1.addEdge("1","2");
        g1.addEdge("1","4");
        g1.addEdge("2","3");
        g1.addEdge("4","3");
        g1.addEdge("1","3");

        System.out.println("the graph is ----: "+g1.printGraph());

    }
}
