/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package LinkedList;
import LinkedList.Node;

public class LinkedList {

    Node head;
    public void insert (String data){
        if (this.head==null) {
            this.head = new Node(data);
//            System.out.println(this.head.value);


        }else{
            Node current = this.head;
            this.head= new Node(data);
            this.head.next= current;
//            System.out.println(this.head.value);

        }

    }
    public boolean includes(String value){
        Node current = this.head;
        while(current.getNext() != null){
            System.out.println("curenc"+current.value);
            if (current.value==value){
                return true;
            }
            current = current.getNext();
        }
        if (current.value==value){
            return true;
        }else{
            return false;

        }
    }
    public String to_string(){
        String allValues= "";
        Node current = this.head;
        while (current.getNext() != null){
            allValues = allValues+current.value+"<<" ;
            current=current.getNext();

        }
        allValues += current.value;
        return allValues;
    }

}


