/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package LinkedList;

public class LinkedList {

    Node head;
    public void insert (String data){
        if (this.head==null) {
            this.head = new Node(data);
//            System.out.println(this.head.value);


        }else{
            Node current = this.head;
            this.head= new Node(data);
            this.head.next= current;
//            System.out.println(this.head.value);

        }

    }
    public boolean includes(String value){
        Node current = this.head;
        while(current.getNext() != null){
            if (current.value==value){
                return true;
            }
            current = current.getNext();
        }
        if (current.value==value){
            return true;
        }else{
            return false;

        }
    }
    public String to_string(){
        String allValues= "";
        Node current = this.head;
        while (current.getNext() != null){
            allValues = allValues+current.value+"<<" ;
            current=current.getNext();

        }
        allValues += current.value;
        return allValues;
    }

    public void append(String newvalue){
        Node current = this.head;
        Node newNode = new Node(newvalue);

        if (this.head == null){
            this.head=newNode;
        }else{
            while(current.getNext() != null){
                current = current.getNext();
            }
            current.next= newNode;
        }
    }
     public void insertBefore(String v1, String v2){
        Node newNode = new Node(v2);
        Node current= this.head;
        Node previousNode= current;
        while(  current.getNext() != null ){
            if (current.value == v1){
                newNode.next=current;
                previousNode.next=newNode;
                break;
            }
            previousNode= current;
            current = current.getNext();
        }

     }
    public void insertAfter(String v1, String v2){
        Node newNode = new Node(v2);
        Node current= this.head;
        Node afterCurrent;
        while(  current.getNext() != null ){
            if (current.value == v1){
                afterCurrent= current.getNext();
                current.next=newNode;
                newNode.next=afterCurrent;
                break;
            }
            current = current.getNext();
        }
    }
    /* Code Challenge: Class 07
     */
    public int size(){
        Node current = this.head;
        int nodesNumber=1;
        while(current.getNext() != null){
            nodesNumber +=1;
            current = current.getNext();

        }
        return nodesNumber;

    }
    public String kthFromEnd(int k){
        Node current= this.head;
        int index= this.size()-k;
        System.out.println(index);
        String kthValue="0";
        if (k<0){
            return "you enter negative value !";
        }
        else if (index <0){
            return "the k value is bigger than the array size";
        }else{
            for (int i=0; i< index;i++){
                kthValue= current.value;
                current= current.getNext();
            }
            return kthValue;
        }
    }





}


