/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package hashtable;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class LibraryTest {
    private HashTable<String,String> hashTable;

    @BeforeEach
    void pickup(){
        hashTable= new HashTable<>();
        hashTable.add("Name","Ahmad");

    }
    // test add
    @Test
    void addTest(){
        assertTrue(hashTable.contain("Name"));
    }
    // test get
    @Test
    void getTest(){
        assertEquals("Ahmad",hashTable.get("Name"));
    }
    // test getnull
    @Test
    void getNullTest(){
        assertEquals(null,hashTable.get("age"));

    }

    @Test void someLibraryMethodReturnsTrue() {
        Library classUnderTest = new Library();
        assertTrue(classUnderTest.someLibraryMethod(), "someLibraryMethod should return 'true'");
    }
}
