/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package sort;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
    public static void main(String[] args) {

        int[] array=  {8,4,23,42,16,15};
        SelectionSort(array);
        System.out.println(array[0]);
        System.out.println(array[5]);

    }

    public static void  SelectionSort(int [] arr){
        int length=arr.length;

        for (int i=0;i<length;i++){
            int value= arr[i];
            int k=value;
            for(int j=i+1;j<length;j++){
                if (arr[j]<value){
                    value= arr[j];
                    arr[j]=k;
                }
            }
            arr[i]=value;
        }
    }


}
